  $ mkdir docs
Generating odocls for base with odig. This might give an error on some
dependencies so we do not display error (one was encountered with yojson)
  $ odig odoc --cache-dir=docs base 2> /dev/null
  Updating documentation, this may take some time...
  $ ls ./docs/odoc
  base
  ocaml
  ocamlformat-lib
  odoc
  odoc-parser
  odoc-support-files.writes
  sexplib0
  $ ls ./docs/odoc/ocaml
  arith_status.html.writes
  arith_status.odoc
  arith_status.odoc.deps
  arith_status.odoc.writes
  arith_status.odocl
  big_int.html.writes
  big_int.odoc
  big_int.odoc.deps
  big_int.odoc.writes
  big_int.odocl
  bigarray.html.writes
  bigarray.odoc
  bigarray.odoc.deps
  bigarray.odoc.writes
  bigarray.odocl
  camlinternalAtomic.html.writes
  camlinternalAtomic.odoc
  camlinternalAtomic.odoc.deps
  camlinternalAtomic.odoc.writes
  camlinternalAtomic.odocl
  camlinternalFormat.html.writes
  camlinternalFormat.odoc
  camlinternalFormat.odoc.deps
  camlinternalFormat.odoc.writes
  camlinternalFormat.odocl
  camlinternalFormatBasics.html.writes
  camlinternalFormatBasics.odoc
  camlinternalFormatBasics.odoc.deps
  camlinternalFormatBasics.odoc.writes
  camlinternalFormatBasics.odocl
  camlinternalLazy.html.writes
  camlinternalLazy.odoc
  camlinternalLazy.odoc.deps
  camlinternalLazy.odoc.writes
  camlinternalLazy.odocl
  camlinternalMod.html.writes
  camlinternalMod.odoc
  camlinternalMod.odoc.deps
  camlinternalMod.odoc.writes
  camlinternalMod.odocl
  camlinternalOO.html.writes
  camlinternalOO.odoc
  camlinternalOO.odoc.deps
  camlinternalOO.odoc.writes
  camlinternalOO.odocl
  compiler-libs
  dynlink.html.writes
  dynlink.odoc
  dynlink.odoc.deps
  dynlink.odoc.writes
  dynlink.odocl
  index.mld
  nat.html.writes
  nat.odoc
  nat.odoc.deps
  nat.odoc.writes
  nat.odocl
  num.html.writes
  num.odoc
  num.odoc.deps
  num.odoc.writes
  num.odocl
  ocaml.html.deps
  ocamldoc
  page-index.html.writes
  page-index.odoc
  page-index.odoc.writes
  page-index.odocl
  profiling.html.writes
  profiling.odoc
  profiling.odoc.deps
  profiling.odoc.writes
  profiling.odocl
  ratio.html.writes
  ratio.odoc
  ratio.odoc.deps
  ratio.odoc.writes
  ratio.odocl
  std_exit.html.writes
  std_exit.odoc
  std_exit.odoc.deps
  std_exit.odoc.writes
  std_exit.odocl
  stdlib.html.writes
  stdlib.odoc
  stdlib.odoc.deps
  stdlib.odoc.writes
  stdlib.odocl
  stdlib__Arg.html.writes
  stdlib__Arg.odoc
  stdlib__Arg.odoc.deps
  stdlib__Arg.odoc.writes
  stdlib__Arg.odocl
  stdlib__Array.html.writes
  stdlib__Array.odoc
  stdlib__Array.odoc.deps
  stdlib__Array.odoc.writes
  stdlib__Array.odocl
  stdlib__ArrayLabels.html.writes
  stdlib__ArrayLabels.odoc
  stdlib__ArrayLabels.odoc.deps
  stdlib__ArrayLabels.odoc.writes
  stdlib__ArrayLabels.odocl
  stdlib__Atomic.html.writes
  stdlib__Atomic.odoc
  stdlib__Atomic.odoc.deps
  stdlib__Atomic.odoc.writes
  stdlib__Atomic.odocl
  stdlib__Bigarray.html.writes
  stdlib__Bigarray.odoc
  stdlib__Bigarray.odoc.deps
  stdlib__Bigarray.odoc.writes
  stdlib__Bigarray.odocl
  stdlib__Bool.html.writes
  stdlib__Bool.odoc
  stdlib__Bool.odoc.deps
  stdlib__Bool.odoc.writes
  stdlib__Bool.odocl
  stdlib__Buffer.html.writes
  stdlib__Buffer.odoc
  stdlib__Buffer.odoc.deps
  stdlib__Buffer.odoc.writes
  stdlib__Buffer.odocl
  stdlib__Bytes.html.writes
  stdlib__Bytes.odoc
  stdlib__Bytes.odoc.deps
  stdlib__Bytes.odoc.writes
  stdlib__Bytes.odocl
  stdlib__BytesLabels.html.writes
  stdlib__BytesLabels.odoc
  stdlib__BytesLabels.odoc.deps
  stdlib__BytesLabels.odoc.writes
  stdlib__BytesLabels.odocl
  stdlib__Callback.html.writes
  stdlib__Callback.odoc
  stdlib__Callback.odoc.deps
  stdlib__Callback.odoc.writes
  stdlib__Callback.odocl
  stdlib__Char.html.writes
  stdlib__Char.odoc
  stdlib__Char.odoc.deps
  stdlib__Char.odoc.writes
  stdlib__Char.odocl
  stdlib__Complex.html.writes
  stdlib__Complex.odoc
  stdlib__Complex.odoc.deps
  stdlib__Complex.odoc.writes
  stdlib__Complex.odocl
  stdlib__Digest.html.writes
  stdlib__Digest.odoc
  stdlib__Digest.odoc.deps
  stdlib__Digest.odoc.writes
  stdlib__Digest.odocl
  stdlib__Either.html.writes
  stdlib__Either.odoc
  stdlib__Either.odoc.deps
  stdlib__Either.odoc.writes
  stdlib__Either.odocl
  stdlib__Ephemeron.html.writes
  stdlib__Ephemeron.odoc
  stdlib__Ephemeron.odoc.deps
  stdlib__Ephemeron.odoc.writes
  stdlib__Ephemeron.odocl
  stdlib__Filename.html.writes
  stdlib__Filename.odoc
  stdlib__Filename.odoc.deps
  stdlib__Filename.odoc.writes
  stdlib__Filename.odocl
  stdlib__Float.html.writes
  stdlib__Float.odoc
  stdlib__Float.odoc.deps
  stdlib__Float.odoc.writes
  stdlib__Float.odocl
  stdlib__Format.html.writes
  stdlib__Format.odoc
  stdlib__Format.odoc.deps
  stdlib__Format.odoc.writes
  stdlib__Format.odocl
  stdlib__Fun.html.writes
  stdlib__Fun.odoc
  stdlib__Fun.odoc.deps
  stdlib__Fun.odoc.writes
  stdlib__Fun.odocl
  stdlib__Gc.html.writes
  stdlib__Gc.odoc
  stdlib__Gc.odoc.deps
  stdlib__Gc.odoc.writes
  stdlib__Gc.odocl
  stdlib__Genlex.html.writes
  stdlib__Genlex.odoc
  stdlib__Genlex.odoc.deps
  stdlib__Genlex.odoc.writes
  stdlib__Genlex.odocl
  stdlib__Hashtbl.html.writes
  stdlib__Hashtbl.odoc
  stdlib__Hashtbl.odoc.deps
  stdlib__Hashtbl.odoc.writes
  stdlib__Hashtbl.odocl
  stdlib__In_channel.html.writes
  stdlib__In_channel.odoc
  stdlib__In_channel.odoc.deps
  stdlib__In_channel.odoc.writes
  stdlib__In_channel.odocl
  stdlib__Int.html.writes
  stdlib__Int.odoc
  stdlib__Int.odoc.deps
  stdlib__Int.odoc.writes
  stdlib__Int.odocl
  stdlib__Int32.html.writes
  stdlib__Int32.odoc
  stdlib__Int32.odoc.deps
  stdlib__Int32.odoc.writes
  stdlib__Int32.odocl
  stdlib__Int64.html.writes
  stdlib__Int64.odoc
  stdlib__Int64.odoc.deps
  stdlib__Int64.odoc.writes
  stdlib__Int64.odocl
  stdlib__Lazy.html.writes
  stdlib__Lazy.odoc
  stdlib__Lazy.odoc.deps
  stdlib__Lazy.odoc.writes
  stdlib__Lazy.odocl
  stdlib__Lexing.html.writes
  stdlib__Lexing.odoc
  stdlib__Lexing.odoc.deps
  stdlib__Lexing.odoc.writes
  stdlib__Lexing.odocl
  stdlib__List.html.writes
  stdlib__List.odoc
  stdlib__List.odoc.deps
  stdlib__List.odoc.writes
  stdlib__List.odocl
  stdlib__ListLabels.html.writes
  stdlib__ListLabels.odoc
  stdlib__ListLabels.odoc.deps
  stdlib__ListLabels.odoc.writes
  stdlib__ListLabels.odocl
  stdlib__Map.html.writes
  stdlib__Map.odoc
  stdlib__Map.odoc.deps
  stdlib__Map.odoc.writes
  stdlib__Map.odocl
  stdlib__Marshal.html.writes
  stdlib__Marshal.odoc
  stdlib__Marshal.odoc.deps
  stdlib__Marshal.odoc.writes
  stdlib__Marshal.odocl
  stdlib__MoreLabels.html.writes
  stdlib__MoreLabels.odoc
  stdlib__MoreLabels.odoc.deps
  stdlib__MoreLabels.odoc.writes
  stdlib__MoreLabels.odocl
  stdlib__Nativeint.html.writes
  stdlib__Nativeint.odoc
  stdlib__Nativeint.odoc.deps
  stdlib__Nativeint.odoc.writes
  stdlib__Nativeint.odocl
  stdlib__Obj.html.writes
  stdlib__Obj.odoc
  stdlib__Obj.odoc.deps
  stdlib__Obj.odoc.writes
  stdlib__Obj.odocl
  stdlib__Oo.html.writes
  stdlib__Oo.odoc
  stdlib__Oo.odoc.deps
  stdlib__Oo.odoc.writes
  stdlib__Oo.odocl
  stdlib__Option.html.writes
  stdlib__Option.odoc
  stdlib__Option.odoc.deps
  stdlib__Option.odoc.writes
  stdlib__Option.odocl
  stdlib__Out_channel.html.writes
  stdlib__Out_channel.odoc
  stdlib__Out_channel.odoc.deps
  stdlib__Out_channel.odoc.writes
  stdlib__Out_channel.odocl
  stdlib__Parsing.html.writes
  stdlib__Parsing.odoc
  stdlib__Parsing.odoc.deps
  stdlib__Parsing.odoc.writes
  stdlib__Parsing.odocl
  stdlib__Pervasives.html.writes
  stdlib__Pervasives.odoc
  stdlib__Pervasives.odoc.deps
  stdlib__Pervasives.odoc.writes
  stdlib__Pervasives.odocl
  stdlib__Printexc.html.writes
  stdlib__Printexc.odoc
  stdlib__Printexc.odoc.deps
  stdlib__Printexc.odoc.writes
  stdlib__Printexc.odocl
  stdlib__Printf.html.writes
  stdlib__Printf.odoc
  stdlib__Printf.odoc.deps
  stdlib__Printf.odoc.writes
  stdlib__Printf.odocl
  stdlib__Queue.html.writes
  stdlib__Queue.odoc
  stdlib__Queue.odoc.deps
  stdlib__Queue.odoc.writes
  stdlib__Queue.odocl
  stdlib__Random.html.writes
  stdlib__Random.odoc
  stdlib__Random.odoc.deps
  stdlib__Random.odoc.writes
  stdlib__Random.odocl
  stdlib__Result.html.writes
  stdlib__Result.odoc
  stdlib__Result.odoc.deps
  stdlib__Result.odoc.writes
  stdlib__Result.odocl
  stdlib__Scanf.html.writes
  stdlib__Scanf.odoc
  stdlib__Scanf.odoc.deps
  stdlib__Scanf.odoc.writes
  stdlib__Scanf.odocl
  stdlib__Seq.html.writes
  stdlib__Seq.odoc
  stdlib__Seq.odoc.deps
  stdlib__Seq.odoc.writes
  stdlib__Seq.odocl
  stdlib__Set.html.writes
  stdlib__Set.odoc
  stdlib__Set.odoc.deps
  stdlib__Set.odoc.writes
  stdlib__Set.odocl
  stdlib__Stack.html.writes
  stdlib__Stack.odoc
  stdlib__Stack.odoc.deps
  stdlib__Stack.odoc.writes
  stdlib__Stack.odocl
  stdlib__StdLabels.html.writes
  stdlib__StdLabels.odoc
  stdlib__StdLabels.odoc.deps
  stdlib__StdLabels.odoc.writes
  stdlib__StdLabels.odocl
  stdlib__Stream.html.writes
  stdlib__Stream.odoc
  stdlib__Stream.odoc.deps
  stdlib__Stream.odoc.writes
  stdlib__Stream.odocl
  stdlib__String.html.writes
  stdlib__String.odoc
  stdlib__String.odoc.deps
  stdlib__String.odoc.writes
  stdlib__String.odocl
  stdlib__StringLabels.html.writes
  stdlib__StringLabels.odoc
  stdlib__StringLabels.odoc.deps
  stdlib__StringLabels.odoc.writes
  stdlib__StringLabels.odocl
  stdlib__Sys.html.writes
  stdlib__Sys.odoc
  stdlib__Sys.odoc.deps
  stdlib__Sys.odoc.writes
  stdlib__Sys.odocl
  stdlib__Uchar.html.writes
  stdlib__Uchar.odoc
  stdlib__Uchar.odoc.deps
  stdlib__Uchar.odoc.writes
  stdlib__Uchar.odocl
  stdlib__Unit.html.writes
  stdlib__Unit.odoc
  stdlib__Unit.odoc.deps
  stdlib__Unit.odoc.writes
  stdlib__Unit.odocl
  stdlib__Weak.html.writes
  stdlib__Weak.odoc
  stdlib__Weak.odoc.deps
  stdlib__Weak.odoc.writes
  stdlib__Weak.odocl
  str.html.writes
  str.odoc
  str.odoc.deps
  str.odoc.writes
  str.odocl
  threads
  topdirs.html.writes
  topdirs.odoc
  topdirs.odoc.deps
  topdirs.odoc.writes
  topdirs.odocl
  unix.html.writes
  unix.odoc
  unix.odoc.deps
  unix.odoc.writes
  unix.odocl
  unixLabels.html.writes
  unixLabels.odoc
  unixLabels.odoc.deps
  unixLabels.odoc.writes
  unixLabels.odocl
  $ find ./docs/odoc/base/ -name '*.odocl' | sort
  ./docs/odoc/base/base.odocl
  ./docs/odoc/base/base__.odocl
  ./docs/odoc/base/base__Applicative.odocl
  ./docs/odoc/base/base__Applicative_intf.odocl
  ./docs/odoc/base/base__Array.odocl
  ./docs/odoc/base/base__Array0.odocl
  ./docs/odoc/base/base__Array_permute.odocl
  ./docs/odoc/base/base__Avltree.odocl
  ./docs/odoc/base/base__Backtrace.odocl
  ./docs/odoc/base/base__Binary_search.odocl
  ./docs/odoc/base/base__Binary_searchable.odocl
  ./docs/odoc/base/base__Binary_searchable_intf.odocl
  ./docs/odoc/base/base__Blit.odocl
  ./docs/odoc/base/base__Blit_intf.odocl
  ./docs/odoc/base/base__Bool.odocl
  ./docs/odoc/base/base__Bool0.odocl
  ./docs/odoc/base/base__Buffer.odocl
  ./docs/odoc/base/base__Buffer_intf.odocl
  ./docs/odoc/base/base__Bytes.odocl
  ./docs/odoc/base/base__Bytes0.odocl
  ./docs/odoc/base/base__Bytes_tr.odocl
  ./docs/odoc/base/base__Char.odocl
  ./docs/odoc/base/base__Char0.odocl
  ./docs/odoc/base/base__Comparable.odocl
  ./docs/odoc/base/base__Comparable_intf.odocl
  ./docs/odoc/base/base__Comparator.odocl
  ./docs/odoc/base/base__Comparisons.odocl
  ./docs/odoc/base/base__Container.odocl
  ./docs/odoc/base/base__Container_intf.odocl
  ./docs/odoc/base/base__Either.odocl
  ./docs/odoc/base/base__Either0.odocl
  ./docs/odoc/base/base__Either_intf.odocl
  ./docs/odoc/base/base__Equal.odocl
  ./docs/odoc/base/base__Error.odocl
  ./docs/odoc/base/base__Exn.odocl
  ./docs/odoc/base/base__Field.odocl
  ./docs/odoc/base/base__Fieldslib.odocl
  ./docs/odoc/base/base__Float.odocl
  ./docs/odoc/base/base__Float0.odocl
  ./docs/odoc/base/base__Floatable.odocl
  ./docs/odoc/base/base__Fn.odocl
  ./docs/odoc/base/base__Formatter.odocl
  ./docs/odoc/base/base__Globalize.odocl
  ./docs/odoc/base/base__Hash.odocl
  ./docs/odoc/base/base__Hash_intf.odocl
  ./docs/odoc/base/base__Hash_set.odocl
  ./docs/odoc/base/base__Hash_set_intf.odocl
  ./docs/odoc/base/base__Hashable.odocl
  ./docs/odoc/base/base__Hashable_intf.odocl
  ./docs/odoc/base/base__Hasher.odocl
  ./docs/odoc/base/base__Hashtbl.odocl
  ./docs/odoc/base/base__Hashtbl_intf.odocl
  ./docs/odoc/base/base__Hex_lexer.odocl
  ./docs/odoc/base/base__Identifiable.odocl
  ./docs/odoc/base/base__Identifiable_intf.odocl
  ./docs/odoc/base/base__Import.odocl
  ./docs/odoc/base/base__Import0.odocl
  ./docs/odoc/base/base__Indexed_container.odocl
  ./docs/odoc/base/base__Indexed_container_intf.odocl
  ./docs/odoc/base/base__Info.odocl
  ./docs/odoc/base/base__Info_intf.odocl
  ./docs/odoc/base/base__Int.odocl
  ./docs/odoc/base/base__Int0.odocl
  ./docs/odoc/base/base__Int32.odocl
  ./docs/odoc/base/base__Int63.odocl
  ./docs/odoc/base/base__Int63_emul.odocl
  ./docs/odoc/base/base__Int64.odocl
  ./docs/odoc/base/base__Int_conversions.odocl
  ./docs/odoc/base/base__Int_intf.odocl
  ./docs/odoc/base/base__Int_math.odocl
  ./docs/odoc/base/base__Intable.odocl
  ./docs/odoc/base/base__Invariant.odocl
  ./docs/odoc/base/base__Invariant_intf.odocl
  ./docs/odoc/base/base__Lazy.odocl
  ./docs/odoc/base/base__Linked_queue.odocl
  ./docs/odoc/base/base__Linked_queue0.odocl
  ./docs/odoc/base/base__List.odocl
  ./docs/odoc/base/base__List0.odocl
  ./docs/odoc/base/base__List1.odocl
  ./docs/odoc/base/base__Map.odocl
  ./docs/odoc/base/base__Map_intf.odocl
  ./docs/odoc/base/base__Maybe_bound.odocl
  ./docs/odoc/base/base__Monad.odocl
  ./docs/odoc/base/base__Monad_intf.odocl
  ./docs/odoc/base/base__Nativeint.odocl
  ./docs/odoc/base/base__Nothing.odocl
  ./docs/odoc/base/base__Obj_array.odocl
  ./docs/odoc/base/base__Obj_local.odocl
  ./docs/odoc/base/base__Option.odocl
  ./docs/odoc/base/base__Option_array.odocl
  ./docs/odoc/base/base__Or_error.odocl
  ./docs/odoc/base/base__Ordered_collection_common.odocl
  ./docs/odoc/base/base__Ordered_collection_common0.odocl
  ./docs/odoc/base/base__Ordering.odocl
  ./docs/odoc/base/base__Poly0.odocl
  ./docs/odoc/base/base__Popcount.odocl
  ./docs/odoc/base/base__Pow_overflow_bounds.odocl
  ./docs/odoc/base/base__Ppx_compare_lib.odocl
  ./docs/odoc/base/base__Ppx_enumerate_lib.odocl
  ./docs/odoc/base/base__Ppx_hash_lib.odocl
  ./docs/odoc/base/base__Pretty_printer.odocl
  ./docs/odoc/base/base__Printf.odocl
  ./docs/odoc/base/base__Queue.odocl
  ./docs/odoc/base/base__Queue_intf.odocl
  ./docs/odoc/base/base__Random.odocl
  ./docs/odoc/base/base__Random_repr.odocl
  ./docs/odoc/base/base__Ref.odocl
  ./docs/odoc/base/base__Result.odocl
  ./docs/odoc/base/base__Sequence.odocl
  ./docs/odoc/base/base__Set.odocl
  ./docs/odoc/base/base__Set_intf.odocl
  ./docs/odoc/base/base__Sexp.odocl
  ./docs/odoc/base/base__Sexp_with_comparable.odocl
  ./docs/odoc/base/base__Sexpable.odocl
  ./docs/odoc/base/base__Sign.odocl
  ./docs/odoc/base/base__Sign0.odocl
  ./docs/odoc/base/base__Sign_or_nan.odocl
  ./docs/odoc/base/base__Source_code_position.odocl
  ./docs/odoc/base/base__Source_code_position0.odocl
  ./docs/odoc/base/base__Stack.odocl
  ./docs/odoc/base/base__Stack_intf.odocl
  ./docs/odoc/base/base__Staged.odocl
  ./docs/odoc/base/base__String.odocl
  ./docs/odoc/base/base__String0.odocl
  ./docs/odoc/base/base__Stringable.odocl
  ./docs/odoc/base/base__Sys.odocl
  ./docs/odoc/base/base__Sys0.odocl
  ./docs/odoc/base/base__T.odocl
  ./docs/odoc/base/base__Type_equal.odocl
  ./docs/odoc/base/base__Uchar.odocl
  ./docs/odoc/base/base__Uchar0.odocl
  ./docs/odoc/base/base__Uniform_array.odocl
  ./docs/odoc/base/base__Unit.odocl
  ./docs/odoc/base/base__Variant.odocl
  ./docs/odoc/base/base__Variantslib.odocl
  ./docs/odoc/base/base__With_return.odocl
  ./docs/odoc/base/base__Word_size.odocl
  ./docs/odoc/base/base_internalhash_types/base_internalhash_types.odocl
  ./docs/odoc/base/caml/caml.odocl
  ./docs/odoc/base/md5/md5_lib.odocl
  ./docs/odoc/base/page-index.odocl
  ./docs/odoc/base/shadow_stdlib/shadow_stdlib.odocl
  $ cat $(find ./docs/odoc/base/ -name '*.odocl') > megaodocl
  $ du -sh megaodocl
  6.2M	megaodocl
  $ sherlodoc index --index-docstring=true --index-name=true --type-search=true --format=js --db=db.js $(find ./docs/odoc/base/ -name '*.odocl') > /dev/null

  $ gzip -k db.js

We want to compare the compressed size with the size of the odocl. The search
database contains information than the odocl, but the information is organised
in queryable way, so a size increase is expected. It should just be reasonable.
  $ gzip -k megaodocl

  $ du -s *.js *.gz
  2108	db.js
  1592	db.js.gz
  1776	megaodocl.gz

  $ for f in $(find . -name '*.odocl'); do
  >  odoc html-generate --search-uri=db.js --search-uri=sherlodoc.js --output-dir html $f
  > done
  $ odoc support-files -o html
  $ cp db.js html/
The --no-preserve flag is here so that copying to /tmp will not fail because of
a previous run. .js files built by dune are read only.
  $ cp --no-preserve=mode,ownership ../../jsoo/main.bc.js html/sherlodoc.js
  $ du -sh html/sherlodoc.js
  100K	html/sherlodoc.js
  $ ls html
  base
  db.js
  fonts
  highlight.pack.js
  katex.min.css
  katex.min.js
  ocaml
  odoc.css
  odoc_search.js
  sexplib0
  sherlodoc.js
indent to see results
$ cp -r html /tmp
$ firefox /tmp/html/base/index.html
